/**
 * Hududlar ma'lumotnomasi.
 * Rasmiy klassifikator kodlari asosida.
 *
 * Markaz (0) rasmiy ro'yxatda yo'q - korxona tuzilmasi uchun qo'shilgan.
 */

export interface RegionSeed {
  code: number;
  name: string;
  districts: { code: number; name: string }[];
}

export const REGIONS: RegionSeed[] = [
  { code: 0, name: 'Markaz', districts: [] },

  {
    code: 3,
    name: 'Andijon viloyati',
    districts: [
      { code: 1, name: 'Andijon shahar' },
      { code: 3, name: 'Xonobod shahar' },
      { code: 6, name: "Oltinko'l tumani" },
      { code: 7, name: 'Andijon tumani' },
      { code: 8, name: 'Baliqchi tumani' },
      { code: 9, name: "Bo'ston tumani" },
      { code: 10, name: 'Buloqboshi tumani' },
      { code: 11, name: 'Jalaquduq tumani' },
      { code: 12, name: 'Izboskan tumani' },
      { code: 13, name: "Ulug'nor tumani" },
      { code: 14, name: "Qo'rg'ontepa tumani" },
      { code: 15, name: 'Asaka tumani' },
      { code: 16, name: 'Marhamat tumani' },
      { code: 17, name: 'Shahrixon tumani' },
      { code: 18, name: 'Paxtaobod tumani' },
      { code: 19, name: "Xo'jaobod tumani" },
    ],
  },

  {
    code: 6,
    name: 'Buxoro viloyati',
    districts: [
      { code: 1, name: 'Buxoro shahar' },
      { code: 3, name: 'Kogon shahar' },
      { code: 4, name: 'Olot tumani' },
      { code: 5, name: 'Buxoro tumani' },
      { code: 6, name: 'Vobkent tumani' },
      { code: 7, name: "G'ijduvon tumani" },
      { code: 8, name: 'Jondor tumani' },
      { code: 9, name: 'Kogon tumani' },
      { code: 10, name: "Qorako'l tumani" },
      { code: 11, name: 'Peshku tumani' },
      { code: 12, name: 'Romitan tumani' },
      { code: 13, name: 'Shofirkon tumani' },
      { code: 14, name: 'Qorovulbozor tumani' },
    ],
  },

  {
    code: 8,
    name: 'Jizzax viloyati',
    districts: [
      { code: 1, name: 'Arnasoy tumani' },
      { code: 2, name: 'Baxmal tumani' },
      { code: 3, name: "G'allaorol tumani" },
      { code: 4, name: 'Sh.Rashidov tumani' },
      { code: 5, name: "Do'stlik tumani" },
      { code: 6, name: 'Zarbdor tumani' },
      { code: 7, name: 'Zomin tumani' },
      { code: 8, name: 'Zafarobod tumani' },
      { code: 9, name: "Mirzacho'l tumani" },
      { code: 10, name: 'Paxtakor tumani' },
      { code: 11, name: 'Forish tumani' },
      { code: 12, name: 'Jizzax shahri' },
      { code: 13, name: 'Yangiobod tumani' },
    ],
  },

  {
    code: 10,
    name: 'Qashqadaryo viloyati',
    districts: [
      { code: 1, name: 'Qarshi shahri' },
      { code: 2, name: 'Shahrisabz shahar' },
      { code: 4, name: "G'uzor tumani" },
      { code: 5, name: 'Dehqonobod tumani' },
      { code: 6, name: 'Qamashi tumani' },
      { code: 7, name: 'Qarshi tumani' },
      { code: 8, name: 'Koson tumani' },
      { code: 9, name: 'Kitob tumani' },
      { code: 10, name: 'Muborak tumani' },
      { code: 11, name: 'Nishon tumani' },
      { code: 12, name: 'Kasbi tumani' },
      { code: 14, name: 'Chiroqchi tumani' },
      { code: 15, name: 'Shahrisabz tumani' },
      { code: 16, name: "Yakkabog' tumani" },
      { code: 17, name: 'Mirishkor tumani' },
      { code: 18, name: "Ko'kdala tumani" },
    ],
  },

  {
    code: 12,
    name: 'Navoiy viloyati',
    districts: [
      { code: 1, name: 'Navoiy shahar' },
      { code: 2, name: 'Zarafshon shahar' },
      { code: 3, name: 'Uchquduq tumani' },
      { code: 4, name: 'Konimex tumani' },
      { code: 5, name: 'Qiziltepa tumani' },
      { code: 7, name: 'Tomdi tumani' },
      { code: 8, name: 'Navbahor tumani' },
      { code: 9, name: 'Xatirchi tumani' },
      { code: 10, name: 'Nurota tumani' },
      { code: 11, name: 'Karmana tumani' },
      { code: 13, name: "G'azg'on shahar" },
    ],
  },

  {
    code: 14,
    name: 'Namangan viloyati',
    districts: [
      { code: 1, name: 'Namangan shahar' },
      { code: 7, name: 'Mingbuloq tumani' },
      { code: 8, name: 'Kosonsoy tumani' },
      { code: 9, name: 'Namangan tumani' },
      { code: 10, name: 'Norin tumani' },
      { code: 11, name: 'Pop tumani' },
      { code: 12, name: "To'raqo'rg'on tumani" },
      { code: 13, name: 'Uychi tumani' },
      { code: 14, name: "Uchqo'rg'on tumani" },
      { code: 15, name: 'Chortoq tumani' },
      { code: 16, name: 'Chust tumani' },
      { code: 17, name: "Yangiqo'rg'on tumani" },
      { code: 18, name: 'Davlatobod tumani' },
      { code: 19, name: 'Yangi Namangan tumani' },
    ],
  },

  {
    code: 18,
    name: 'Samarqand viloyati',
    districts: [
      { code: 1, name: 'Samarqand shahri' },
      { code: 4, name: 'Tayloq tumani' },
      { code: 6, name: "Kattaqo'rg'on shahri" },
      { code: 8, name: 'Oqdaryo tumani' },
      { code: 9, name: "Bulung'ur tumani" },
      { code: 11, name: 'Jomboy tumani' },
      { code: 12, name: 'Ishtixon tumani' },
      { code: 13, name: "Kattaqo'rg'on tumani" },
      { code: 14, name: "Qo'shrabot tumani" },
      { code: 15, name: 'Narpay tumani' },
      { code: 17, name: 'Payariq tumani' },
      { code: 18, name: "Pastdarg'om tumani" },
      { code: 19, name: 'Paxtachi tumani' },
      { code: 20, name: 'Samarqand tumani' },
      { code: 21, name: 'Nurobod tumani' },
      { code: 22, name: 'Urgut tumani' },
    ],
  },

  {
    code: 22,
    name: 'Surxondaryo viloyati',
    districts: [
      { code: 1, name: 'Termiz shahar' },
      { code: 3, name: 'Angor tumani' },
      { code: 4, name: 'Oltinsoy tumani' },
      { code: 5, name: 'Boysun tumani' },
      { code: 6, name: 'Muzrabod tumani' },
      { code: 7, name: 'Denov tumani' },
      { code: 8, name: "Jarqo'rg'on tumani" },
      { code: 9, name: "Qumqo'rg'on tumani" },
      { code: 10, name: 'Qiziriq tumani' },
      { code: 11, name: 'Sariosiyo tumani' },
      { code: 12, name: 'Termiz tumani' },
      { code: 13, name: 'Sherobod tumani' },
      { code: 14, name: "Sho'rchi tumani" },
      { code: 15, name: 'Uzun tumani' },
      { code: 16, name: 'Bandixon tumani' },
    ],
  },

  {
    code: 24,
    name: 'Sirdaryo viloyati',
    districts: [
      { code: 1, name: 'Oqoltin tumani' },
      { code: 2, name: 'Boyovut tumani' },
      { code: 3, name: 'Guliston tumani' },
      { code: 5, name: 'Mirzaobod tumani' },
      { code: 6, name: 'Sayxunobod tumani' },
      { code: 7, name: 'Sirdaryo tumani' },
      { code: 8, name: 'Xovos tumani' },
      { code: 9, name: 'Sardoba tumani' },
      { code: 10, name: 'Guliston shahar' },
      { code: 12, name: 'Shirin shahar' },
      { code: 13, name: 'Yangiyer shahar' },
    ],
  },

  {
    code: 26,
    name: 'Toshkent shahri',
    districts: [
      { code: 1, name: 'Mirobod tumani' },
      { code: 2, name: "Mirzo Ulug'bek tumani" },
      { code: 3, name: 'Yunusobod tumani' },
      { code: 4, name: 'Yakkasaroy tumani' },
      { code: 5, name: 'Shayxontohur tumani' },
      { code: 6, name: 'Chilonzor tumani' },
      { code: 7, name: 'Sergeli tumani' },
      { code: 8, name: 'Yashnobod tumani' },
      { code: 9, name: 'Olmazor tumani' },
      { code: 10, name: 'Uchtepa tumani' },
      { code: 11, name: 'Bektemir tumani' },
      { code: 12, name: 'Yangihayot tumani' },
    ],
  },

  {
    code: 27,
    name: 'Toshkent viloyati',
    districts: [
      { code: 1, name: 'Bekobod tumani' },
      { code: 2, name: "Bo'ka tumani" },
      { code: 3, name: "Bo'stonliq tumani" },
      { code: 4, name: 'Zangiota tumani' },
      { code: 5, name: 'Yuqori-Chirchiq tumani' },
      { code: 6, name: 'Qibray tumani' },
      { code: 7, name: "Oqqo'rg'on tumani" },
      { code: 8, name: 'Ohangaron tumani' },
      { code: 9, name: 'Parkent tumani' },
      { code: 10, name: 'Pskent tumani' },
      { code: 11, name: 'Toshkent tumani' },
      { code: 12, name: "O'rta-Chirchiq tumani" },
      { code: 13, name: 'Chinoz tumani' },
      { code: 14, name: 'Quyi-Chirchiq tumani' },
      { code: 15, name: "Yangiyo'l tumani" },
      { code: 16, name: 'Angren shahri' },
      { code: 17, name: 'Bekobod shahri' },
      { code: 18, name: 'Olmaliq shahri' },
      { code: 19, name: 'Ohangaron shahar' },
      { code: 20, name: 'Chirchiq shahri' },
      { code: 22, name: "Yangiyo'l shahar" },
      { code: 23, name: 'Nurafshon shahri' },
    ],
  },

  {
    code: 30,
    name: "Farg'ona viloyati",
    districts: [
      { code: 1, name: 'Quvasoy shahri' },
      { code: 3, name: "Qo'qon shahri" },
      { code: 4, name: "Marg'ilon shahri" },
      { code: 5, name: "Farg'ona shahri" },
      { code: 6, name: 'Beshariq tumani' },
      { code: 7, name: "Bog'dod tumani" },
      { code: 8, name: 'Buvayda tumani' },
      { code: 9, name: "Dang'ara tumani" },
      { code: 10, name: 'Yozyovon tumani' },
      { code: 11, name: 'Quva tumani' },
      { code: 12, name: 'Oltiariq tumani' },
      { code: 13, name: 'Qushtepa tumani' },
      { code: 14, name: 'Rishton tumani' },
      { code: 15, name: "So'x tumani" },
      { code: 16, name: 'Toshloq tumani' },
      { code: 17, name: "O'zbekiston tumani" },
      { code: 18, name: "Uchko'prik tumani" },
      { code: 19, name: "Farg'ona tumani" },
      { code: 20, name: 'Furqat tumani' },
    ],
  },

  {
    code: 33,
    name: 'Xorazm viloyati',
    districts: [
      { code: 1, name: 'Urganch shahar' },
      { code: 2, name: 'Xiva shahar' },
      { code: 4, name: 'Urganch tumani' },
      { code: 5, name: 'Xiva tumani' },
      { code: 6, name: 'Xazarasp tumani' },
      { code: 7, name: 'Gurlan tumani' },
      { code: 8, name: 'Shovot tumani' },
      { code: 9, name: 'Yangiariq tumani' },
      { code: 10, name: "Qo'shko'pir tumani" },
      { code: 11, name: "Bog'ot tumani" },
      { code: 12, name: 'Honqa tumani' },
      { code: 13, name: 'Yangibozor tumani' },
      { code: 14, name: "Tuproqqal'a tumani" },
    ],
  },

  {
    code: 35,
    name: "Qoraqalpog'iston Respublikasi",
    districts: [
      { code: 1, name: 'Nukus shahri' },
      { code: 8, name: 'Amudaryo tumani' },
      { code: 9, name: 'Beruniy tumani' },
      { code: 10, name: "Bo'zatov tumani" },
      { code: 11, name: 'Kegeyli tumani' },
      { code: 12, name: "Qo'ng'irot tumani" },
      { code: 13, name: "Qonliko'l tumani" },
      { code: 14, name: "Mo'ynoq tumani" },
      { code: 15, name: 'Nukus tumani' },
      { code: 16, name: "Taxtako'pir tumani" },
      { code: 17, name: "To'rtko'l tumani" },
      { code: 18, name: "Xo'jayli tumani" },
      { code: 19, name: 'Chimboy tumani' },
      { code: 20, name: "Sho'manoy tumani" },
      { code: 21, name: "Ellikqal'a tumani" },
      { code: 22, name: "Qorao'zak tumani" },
      { code: 23, name: 'Taxiatosh tumani' },
    ],
  },
];

/** Bo'limlar - faqat markazda */
export const DEPARTMENTS = [
  { index: 1, code: 'AUP', name: 'AUP' },
  { index: 2, code: 'STRATEGIYA', name: 'Strategiya' },
  { index: 3, code: 'KORP_BOSHQARUV', name: 'Korporativ boshqaruv' },
  { index: 4, code: 'KOMPLEANS', name: 'Kompleans' },
  { index: 5, code: 'YURIST', name: 'Yurist' },
  { index: 6, code: 'KADR', name: 'Kadrlar' },
  { index: 7, code: 'ICHKI_AUDIT', name: 'Ichki audit' },
  { index: 8, code: 'BUX_HISOB', name: 'Buxgalteriya hisobi bo\u2018limi' },
  {
    index: 9,
    code: 'BUX_XIZMAT',
    name: 'Soliq to\u2018lovchilarga buxgalteriya xizmatlarini ko\u2018rsatish bo\u2018limi',
  },
  {
    index: 10,
    code: 'STXKM',
    name: 'Soliq to\u2018lovchilarga xizmat ko\u2018rsatish markazi',
  },
  { index: 11, code: 'FERMER', name: 'Fermer xo\u2018jaliklariga xizmat ko\u2018rsatish' },
  {
    index: 12,
    code: 'FERMER_HUDUD',
    name: 'Fermer xo\u2018jaliklariga xizmat ko\u2018rsatishni muvofiqlashtirish (hudud)',
  },
  { index: 13, code: 'HUDUD_MUVOF', name: 'Hududlarni muvofiqlashtirish' },
  { index: 14, code: 'DAST_MAHSULOT', name: 'Dasturiy mahsulotlar' },
  {
    index: 15,
    code: 'LOYIHA_MEN',
    name: 'Dasturiy mahsulotlarni muvofiqlashtirish bo\u2018yicha loyiha menejerlari sho\u2018basi',
  },
  { index: 16, code: 'RAQAMLI_MARKAZ', name: 'Raqamli texnologiyalar xalqaro markazi' },
  { index: 17, code: 'AXBOROT', name: 'Axborot xizmati' },
  { index: 18, code: 'TOLOV_MARKETING', name: 'To\u2018lov tizimi va marketing' },
  { index: 19, code: 'BOZOR_NARXI', name: 'Bozor narxi' },
  { index: 20, code: 'MARKSHEYDER', name: 'Marksheyder' },
  { index: 21, code: 'TAX_FREE', name: 'Tax free' },
  { index: 22, code: 'CALL_MARKAZ', name: 'Call markaz' },
  {
    index: 23,
    code: 'MUROJAAT',
    name: 'Murojaatlar bilan ishlash va ijro nazorati',
  },
  { index: 24, code: 'XARIDLAR', name: 'Xaridlar va xo\u2018jalik ishlari bo\u2018yicha' },
  { index: 25, code: 'TEXNIK', name: 'Texnik xodimlar' },
  { index: 26, code: 'DSQ', name: 'DSQ' },
];
