import type { CategoryNode, IncomeCategoryNode } from '../types/category';

/**
 * Xarajat kategoriyalari daraxti.
 * Soliq-servis xizmatlari korxonasiga moslashtirilgan.
 *
 * MUHIM: `code` qiymatlari bazada saqlanadi — hech qachon o'zgartirilmasin.
 * `label` ni o'zgartirish xavfsiz.
 */
export const EXPENSE_CATEGORIES: CategoryNode[] = [
  // ═══════════ 1. ISH HAQI FONDI ═══════════
  {
    code: 'PAYROLL',
    label: 'Ish haqi fondi',
    parent: null,
    isLeaf: false,
    behavior: 'MIXED',
    scope: 'DEPARTMENT',
    keywords: [],
    model3d: 'staff',
    order: 100,
  },
  {
    code: 'PAYROLL_BASE',
    label: 'Asosiy ish haqi',
    parent: 'PAYROLL',
    isLeaf: true,
    behavior: 'FIXED',
    scope: 'DEPARTMENT',
    keywords: ['asosiy ish haqi', 'oylik', 'maosh', 'иш ҳақи', 'зарплата', 'оклад', 'salary'],
    order: 101,
  },
  {
    code: 'PAYROLL_BONUS',
    label: 'Mukofot va ustamalar',
    parent: 'PAYROLL',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'DEPARTMENT',
    keywords: ['mukofot', 'ustama', 'bonus', 'премия', 'надбавка', 'мукофот'],
    order: 102,
  },
  {
    code: 'PAYROLL_VACATION',
    label: "Ta'til to'lovlari",
    parent: 'PAYROLL',
    isLeaf: true,
    behavior: 'FIXED',
    scope: 'DEPARTMENT',
    keywords: ['tatil', "ta'til", 'otpusk', 'отпускные', 'таътил'],
    order: 103,
  },
  {
    code: 'PAYROLL_TAX',
    label: 'Ijtimoiy soliq va ajratmalar',
    parent: 'PAYROLL',
    isLeaf: true,
    behavior: 'FIXED',
    scope: 'DEPARTMENT',
    keywords: ['ijtimoiy soliq', 'jshds', 'inps', 'соцналог', 'ндфл', 'единый социальный'],
    order: 104,
  },

  // ═══════════ 2. OFIS VA INFRATUZILMA ═══════════
  {
    code: 'OFFICE',
    label: 'Ofis va infratuzilma',
    parent: null,
    isLeaf: false,
    behavior: 'FIXED',
    scope: 'GENERAL',
    keywords: [],
    model3d: 'office',
    order: 200,
  },
  {
    code: 'OFFICE_RENT',
    label: 'Ijara',
    parent: 'OFFICE',
    isLeaf: true,
    behavior: 'FIXED',
    scope: 'GENERAL',
    keywords: ['ijara', 'arenda', 'аренда', 'ижара'],
    order: 201,
  },
  {
    code: 'OFFICE_UTILITIES',
    label: "Kommunal to'lovlar",
    parent: 'OFFICE',
    isLeaf: true,
    behavior: 'MIXED',
    scope: 'GENERAL',
    keywords: ['kommunal', 'elektr', 'suv', 'gaz', 'isitish', 'коммунальные', 'электричество'],
    order: 202,
  },
  {
    code: 'OFFICE_INTERNET',
    label: 'Internet va aloqa',
    parent: 'OFFICE',
    isLeaf: true,
    behavior: 'FIXED',
    scope: 'GENERAL',
    keywords: ['internet', 'aloqa', 'telefon', 'связь', 'интернет'],
    order: 203,
  },
  {
    code: 'OFFICE_SUPPLIES',
    label: 'Ofis materiallari',
    parent: 'OFFICE',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: ['kantselyariya', 'qogoz', 'kartridj', 'канцтовары', 'бумага'],
    order: 204,
  },
  {
    code: 'OFFICE_EQUIPMENT',
    label: 'Jihozlar va texnika',
    parent: 'OFFICE',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: ['jihoz', 'kompyuter', 'printer', 'mebel', 'оборудование', 'техника'],
    order: 205,
  },
  {
    code: 'OFFICE_REPAIR',
    label: "Ta'mirlash",
    parent: 'OFFICE',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: ['tamirlash', 'remont', 'ремонт'],
    order: 206,
  },

  // ═══════════ 3. DASTURIY TA'MINOT ═══════════
  {
    code: 'SOFTWARE',
    label: "Dasturiy ta'minot va litsenziyalar",
    parent: null,
    isLeaf: false,
    behavior: 'FIXED',
    scope: 'GENERAL',
    keywords: [],
    model3d: 'server',
    order: 300,
  },
  {
    code: 'SOFTWARE_ACCOUNTING',
    label: 'Buxgalteriya dasturlari',
    parent: 'SOFTWARE',
    isLeaf: true,
    behavior: 'FIXED',
    scope: 'GENERAL',
    keywords: ['1c', '1с', 'buxgalteriya dasturi', 'бухгалтерская программа'],
    order: 301,
  },
  {
    code: 'SOFTWARE_REPORTING',
    label: 'Elektron hisobot tizimlari',
    parent: 'SOFTWARE',
    isLeaf: true,
    behavior: 'FIXED',
    scope: 'GENERAL',
    keywords: ['didox', 'soliq dasturi', 'elektron hisobot', 'faktura'],
    order: 302,
  },
  {
    code: 'SOFTWARE_OTHER',
    label: 'Boshqa obunalar',
    parent: 'SOFTWARE',
    isLeaf: true,
    behavior: 'FIXED',
    scope: 'GENERAL',
    keywords: ['obuna', 'litsenziya', 'подписка', 'лицензия', 'subscription'],
    order: 303,
  },

  // ═══════════ 4. TRANSPORT ═══════════
  {
    code: 'TRANSPORT',
    label: 'Transport',
    parent: null,
    isLeaf: false,
    behavior: 'MIXED',
    scope: 'GENERAL',
    keywords: [],
    model3d: 'vehicle',
    order: 400,
  },
  {
    code: 'TRANSPORT_FUEL',
    label: "Yoqilg'i",
    parent: 'TRANSPORT',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: ['yoqilgi', 'benzin', 'gaz', 'dizel', 'топливо', 'бензин'],
    order: 401,
  },
  {
    code: 'TRANSPORT_REPAIR',
    label: 'Texnik xizmat va ta\u2019mirlash',
    parent: 'TRANSPORT',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: ['avto tamirlash', 'texnik korik', 'shina', 'ремонт авто', 'запчасти'],
    order: 402,
  },
  {
    code: 'TRANSPORT_INSURANCE',
    label: 'Sug\u2018urta va soliq',
    parent: 'TRANSPORT',
    isLeaf: true,
    behavior: 'FIXED',
    scope: 'GENERAL',
    keywords: ['sugurta', 'osago', 'страховка', 'транспортный налог'],
    order: 403,
  },
  {
    code: 'TRANSPORT_TAXI',
    label: 'Taksi va yo\u2018l xarajatlari',
    parent: 'TRANSPORT',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'DEPARTMENT',
    keywords: ['taksi', 'yol kira', 'такси', 'проезд', 'komandirovka'],
    order: 404,
  },

  // ═══════════ 5. MARKETING ═══════════
  {
    code: 'MARKETING',
    label: 'Marketing va mijozlar',
    parent: null,
    isLeaf: false,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: [],
    order: 500,
  },
  {
    code: 'MARKETING_ADS',
    label: 'Reklama',
    parent: 'MARKETING',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: ['reklama', 'targeting', 'реклама', 'смм', 'smm'],
    order: 501,
  },
  {
    code: 'MARKETING_EVENTS',
    label: 'Mijoz tadbirlari va vakillik',
    parent: 'MARKETING',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: ['tadbir', 'vakillik', 'мероприятие', 'представительские'],
    order: 502,
  },

  // ═══════════ 6. KADRLAR ═══════════
  {
    code: 'HR',
    label: 'Kadrlar',
    parent: null,
    isLeaf: false,
    behavior: 'VARIABLE',
    scope: 'DEPARTMENT',
    keywords: [],
    order: 600,
  },
  {
    code: 'HR_TRAINING',
    label: 'O\u2018qitish va malaka oshirish',
    parent: 'HR',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'DEPARTMENT',
    keywords: ['oqitish', 'trening', 'seminar', 'kurs', 'обучение', 'тренинг'],
    order: 601,
  },
  {
    code: 'HR_CERTIFICATION',
    label: 'Sertifikat va attestatsiya',
    parent: 'HR',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'DEPARTMENT',
    keywords: ['sertifikat', 'attestatsiya', 'сертификат', 'аттестация'],
    order: 602,
  },
  {
    code: 'HR_RECRUITMENT',
    label: 'Xodim izlash',
    parent: 'HR',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: ['ishga qabul', 'vakansiya', 'подбор персонала', 'вакансия'],
    order: 603,
  },

  // ═══════════ 7. MOLIYAVIY XARAJATLAR ═══════════
  {
    code: 'FINANCE',
    label: 'Moliyaviy xarajatlar',
    parent: null,
    isLeaf: false,
    behavior: 'MIXED',
    scope: 'GENERAL',
    keywords: [],
    order: 700,
  },
  {
    code: 'FINANCE_BANK',
    label: 'Bank xizmatlari',
    parent: 'FINANCE',
    isLeaf: true,
    behavior: 'MIXED',
    scope: 'GENERAL',
    keywords: ['bank xizmati', 'komissiya', 'банковские услуги', 'комиссия'],
    order: 701,
  },
  {
    code: 'FINANCE_INTEREST',
    label: 'Kredit foizlari',
    parent: 'FINANCE',
    isLeaf: true,
    behavior: 'FIXED',
    scope: 'GENERAL',
    keywords: ['kredit foizi', 'foiz', 'проценты по кредиту'],
    order: 702,
  },

  // ═══════════ 8. SOLIQLAR ═══════════
  {
    code: 'TAXES',
    label: 'Soliqlar va yig\u2018imlar',
    parent: null,
    isLeaf: false,
    behavior: 'MIXED',
    scope: 'GENERAL',
    keywords: [],
    order: 800,
  },
  {
    code: 'TAXES_PROFIT',
    label: 'Foyda solig\u2018i',
    parent: 'TAXES',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: ['foyda soligi', 'налог на прибыль'],
    order: 801,
  },
  {
    code: 'TAXES_TURNOVER',
    label: 'Aylanma solig\u2018i',
    parent: 'TAXES',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: ['aylanma soligi', 'налог с оборота'],
    order: 802,
  },
  {
    code: 'TAXES_OTHER',
    label: 'Boshqa soliq va yig\u2018imlar',
    parent: 'TAXES',
    isLeaf: true,
    behavior: 'MIXED',
    scope: 'GENERAL',
    keywords: ['boj', 'yigim', 'пошлина', 'сбор'],
    order: 803,
  },

  // ═══════════ 9. BOSHQA ═══════════
  {
    code: 'OTHER',
    label: 'Boshqa xarajatlar',
    parent: null,
    isLeaf: false,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: [],
    order: 900,
  },
  {
    code: 'OTHER_MISC',
    label: 'Turli xarajatlar',
    parent: 'OTHER',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: [],
    order: 901,
  },
  {
    code: 'UNCATEGORIZED',
    label: 'Aniqlanmagan',
    parent: 'OTHER',
    isLeaf: true,
    behavior: 'VARIABLE',
    scope: 'GENERAL',
    keywords: [],
    order: 999,
  },
];

/**
 * Daromad manbalari.
 * Soliq-servis korxonasi uchun xizmat turlari.
 */
export const INCOME_CATEGORIES: IncomeCategoryNode[] = [
  { code: 'SERVICE_ACCOUNTING', label: 'Buxgalteriya xizmati', order: 10 },
  { code: 'SERVICE_TAX_CONSULT', label: 'Soliq maslahati', order: 20 },
  { code: 'SERVICE_REPORTING', label: 'Hisobot tayyorlash', order: 30 },
  { code: 'SERVICE_AUDIT', label: 'Audit va tekshiruv', order: 40 },
  { code: 'SERVICE_REGISTRATION', label: "Ro'yxatdan o'tkazish", order: 50 },
  { code: 'SERVICE_LEGAL', label: 'Yuridik xizmat', order: 60 },
  { code: 'SERVICE_TRAINING', label: "O'quv kurslari", order: 70 },
  { code: 'SERVICE_OTHER', label: 'Boshqa xizmatlar', order: 90 },
];
